### ISSUE TITLE
command.ws 500 internal server errors

### ISSUE THREAD

**Issue by jquindlen** [ApolloCoinAPX/ApolloCoinWallet#37]
When the crypto price caching server (command.ws) is writing an update to the JSON file, any attempt to read that JSON file while it is being rewritten results in a 500 internal server error resulting in bad prices.

**Comment by jquindlen** [comment]
Alright, I've edited the PHP file so that it returns the last cache data before it starts writing the new cache data.  I also increased php.ini values (which were all at default) in order to let the server actually use all the RAM it has access to and to not timeout so quickly.

**Comment by jquindlen** [comment]
[Sat Jan 29 19:58:03.773147 2022] [php7:error] [pid 40129] [client 174.31.253.113:43084] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `GET https://api.coingecko.com/api/v3/simple/price?ids=ethereum%2Cbitcoin%2Cnano%2Cbinancecoin%2Capollo-coin&vs_currencies=usd` resulted in a `429 Too Many Requests` response:\nerror code: 1015\n in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()\n#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()\n#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Promise\\TaskQueue->run()\n#5 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#6 / in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by jquindlen** [comment]
[Sat Jan 29 19:58:03.773147 2022] [php7:error] [pid 40129] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `GET https://api.coingecko.com/api/v3/simple/price?ids=ethereum%2Cbitcoin%2Cnano%2Cbinancecoin%2Capollo-coin&vs_currencies=usd` resulted in a `429 Too Many Requests` response:\nerror code: 1015\n in guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

**Comment by jquindlen** [comment]
Lowering request rate should fix this

**Comment by jquindlen** [comment]
"Our free API has a rate limit of 10-50 calls per minute, if you exceed that limit you will be blocked until the next 1 minute window" from https://www.coingecko.com/en/api/pricing

**Comment by jquindlen** [comment]
We're making less than 1 call per minute and still getting random 429 Too Many Requests

**Comment by jquindlen** [comment]
Paid for CoinGecko, problem went away
